/**
 * View Segment state
 * @enum {string}
 * @return {{APPLICATION_VIEW:string,HEADER:string,SCREEN_STACK:string,CATEGORY_BUTTON_EXPAND_POOL:string,CATEGORY_BUTTON_EDIT_POOL:string,SUB_CATEGORY_BUTTON_POOL:string}}
 */
App.ViewName = {
    APPLICATION_VIEW:"APPLICATION_VIEW",
    HEADER:"HEADER",
    SCREEN_STACK:"SCREEN_STACK",
    CATEGORY_BUTTON_EXPAND_POOL:"CATEGORY_BUTTON_EXPAND_POOL",
    CATEGORY_BUTTON_EDIT_POOL:"CATEGORY_BUTTON_EDIT_POOL",
    SUB_CATEGORY_BUTTON_POOL:"SUB_CATEGORY_BUTTON_POOL"
};
