/**
 * View Segment state
 * @enum {number}
 * @return {{APPLICATION_VIEW:number,HEADER:number,SCREEN_STACK:number,CATEGORY_BUTTON_EXPAND_POOL:number,CATEGORY_BUTTON_EDIT_POOL:number,SUB_CATEGORY_BUTTON_POOL:number,SKIN:number}}
 */
App.ViewName = {
    APPLICATION_VIEW:0,
    HEADER:1,
    SCREEN_STACK:2,
    CATEGORY_BUTTON_EXPAND_POOL:3,
    CATEGORY_BUTTON_EDIT_POOL:4,
    SUB_CATEGORY_BUTTON_POOL:5,
    SKIN:6
};
